### ISSUE TITLE
Suggestion: Range Table

### ISSUE THREAD

**Issue by CaptainJoy** [MadCoder253/roll20-character-sheets#14]
It would be nice have a Size/Speed/Range table, similar to the Hit Location table, on the Combat tab page.  "Mad Coder 253 rules!" – spoken in football player from Bill & Ted's Excellent Adventure voice

**Comment by TankFarmer** [comment]
I like this and since it is part of the original character sheet and SJ Games states we can make all the character sheets we want, I would assume this will not violate any copy writes. The problem is I know where to put it but it would require capabilities sin coding i do not have yet.
I would put it in place of the Hit Location box on the Combat page and move the Hit Location box to the genera page where it really belongs. Give me some time to work it out.

**Comment by KlingonMike** [comment]
Working on some ideas for this. I started typing all this information into the HTML code and figure that was time consuming and difficult to format. The other option it using part of the table, typing it into <S Word, then taking a Snipit of it and embedding the image into the HTML code. That seems ease to format but I do not know how to code that yet. So I will continue to work on this.

**Comment by KlingonMike** [comment]
Planned for Version 1.3.8 with a PULL request to be made for week of 08/13/2018

**Comment by KlingonMike** [comment]
Implemented successfully with Version 1.3.8 on 8/14/2018. This suggestion can now be closed.
